services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    environment:
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_TEST_DATABASE=${MONGO_TEST_DATABASE}
    ports:
      - "4000:4000"
    volumes:
      - ./api:/api
    develop:
      watch:
        - action: sync
          path: ./api
          target: /api
        - action: rebuild
          path: api/package.json

  database:
    container_name: mongo
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=mongodb
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
volumes:
  data:
    driver: local
